name: im_flutter_sdk_interface
description: "A new Flutter plugin project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.4.0
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.7

dev_dependencies:
  flutter_lints: ^3.0.0
