name: im_flutter_sdk_android
description: Integrate the Chat SDK to enjoy the global IM services with high reliability, ultra-low latency, and high concurrency.
version: 4.19.2
homepage: https://www.easemob.com

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

  # im_flutter_sdk_interface: ^4.15.0+1
  im_flutter_sdk_interface:
    path: ../im_flutter_sdk_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

  plugin:
    implements: im_flutter_sdk
    platforms:
      android:
        dartPluginClass: ClientAndroid
        package: com.easemob.im_flutter_sdk
        pluginClass: ImFlutterSdkPlugin
