name: android-500-topo-2dev

accounts:
  account_a:
    provision: rest
  account_b:
    provision: rest

devices:
  device_a:
    device_name: deviceA
    platform: android
    sdk_version: 5.0.0
    account: account_a
    serial: emulator-5554

  device_b:
    device_name: deviceB
    platform: android
    sdk_version: 5.0.0
    account: account_b
    serial: emulator-5558

topologies:
  account_a_to_account_b:
    sender:
      account: account_a
      action_device: device_a
    recipient:
      account: account_b
      action_device: device_b

  account_b_to_account_a:
    sender:
      account: account_b
      action_device: device_b
    recipient:
      account: account_a
      action_device: device_a

runner:
  start_emulators: false
  device_ready_timeout: 180
  hello_timeout: 30
  start_retry: 1
  keep_device_alive: true
