import 'dart:convert';
import 'dart:io';

const _placeholderPrefix = 'TODO';

/// Local files the example reads. The project configures a single environment:
/// `config.local.json` holds its credentials and test data, and
/// `lib/env.dart` is the generated Dart view of it.
class EnvPaths {
  EnvPaths(this.exampleDir);

  factory EnvPaths.fromScript() {
    return EnvPaths(File.fromUri(Platform.script).parent.parent);
  }

  final Directory exampleDir;

  File get configTemplate =>
      File('${exampleDir.path}/templates/config.local.example.json');
  File get envTemplate => File('${exampleDir.path}/templates/env.example.dart');
  File get localConfig => File('${exampleDir.path}/config.local.json');
  File get activeEnv => File('${exampleDir.path}/lib/env.dart');
}

Future<void> main(List<String> args) async {
  final paths = EnvPaths.fromScript();
  final command = args.isEmpty ? 'help' : args.first;
  try {
    switch (command) {
      case 'ensure':
        await ensureLocalFiles(paths);
        break;
      case 'gettoken':
        await ensureLocalFiles(paths);
        await generateEnvironment(paths);
        break;
      case 'help':
      case '--help':
      case '-h':
        stdout.writeln('''
Usage:
  dart run tool/env_tool.dart ensure
  dart run tool/env_tool.dart gettoken
''');
        break;
      default:
        throw FormatException('Unknown command: $command');
    }
  } catch (error) {
    stderr.writeln('env_tool: $error');
    exitCode = 1;
  }
}

Future<void> ensureLocalFiles(EnvPaths paths) async {
  await _copyIfMissing(paths.configTemplate, paths.localConfig);
  await _copyIfMissing(paths.envTemplate, paths.activeEnv);
}

Future<void> _copyIfMissing(File source, File target) async {
  if (await target.exists()) {
    stdout.writeln('Skip: ${target.path} already exists');
    return;
  }
  await target.parent.create(recursive: true);
  await target.writeAsString(await source.readAsString(), flush: true);
  await _restrictPermissions(target);
  stdout.writeln('Created: ${target.path}');
}

/// Fetches one user token per configured account and writes the result to
/// `lib/env.dart`. Switching environments means editing `config.local.json`.
Future<void> generateEnvironment(EnvPaths paths) async {
  final config = await _readJsonObject(paths.localConfig);
  _validateConfigShape(config);
  _requireCredentials(config);

  final tokenClient = TokenClient();
  try {
    final appToken = await tokenClient.fetchAppToken(config);
    final accounts = await tokenClient.fetchUserTokens(
      config: config,
      appToken: appToken,
    );
    final environment = buildEnvironment(config: config, accounts: accounts);
    await _atomicWrite(paths.activeEnv, renderEnvironmentDart(environment));
    stdout.writeln(
      'Generated ${paths.activeEnv.path} (${accounts.length} accounts)',
    );
  } finally {
    tokenClient.close();
  }
}

/// The example environment handed to the app: chat options, the app key, the
/// per-account user tokens, and the test resources referenced by the scripts.
Map<String, Object?> buildEnvironment({
  required Map<String, dynamic> config,
  required List<Map<String, Object?>> accounts,
}) {
  final environment = <String, Object?>{};
  environment.addAll(_optionalMap(config['chatOptions']));
  environment.addAll({
    'appKey': config['appKey'],
    'accounts': accounts,
    'groups': _resources(config['groups']),
    'rooms': _resources(config['rooms']),
  });

  if (config['enablePrivateConfig'] == true) {
    final requiredServers = <String, Object?>{
      'webSocketServer': config['webSocketServer'],
      'restServer': config['restServer'],
      'imServer': config['imServer'] ?? config['msyncServer'],
    };
    final missing = requiredServers.entries
        .where((entry) => _isPlaceholder(entry.value))
        .map((entry) => entry.key)
        .toList();
    if (missing.isNotEmpty) {
      throw FormatException(
        'enablePrivateConfig requires ${missing.join(', ')}',
      );
    }
    environment['enableDNSConfig'] = false;
    environment.addAll(requiredServers);
    for (final key in const ['imPort', 'webSocketPort']) {
      final value = config[key];
      if (value is int && value > 0) environment[key] = value;
    }
  }
  return environment;
}

List<Map<String, Object?>> _resources(Object? raw) {
  return [
    for (final value in raw is List ? raw : const [])
      if (value is Map)
        <String, Object?>{
          for (final entry in value.entries)
            // A leftover `cluster` key from an older multi-cluster config is
            // dropped: this tool generates one environment.
            if (entry.key != 'cluster') entry.key.toString(): entry.value,
        },
  ];
}

String renderEnvironmentDart(Map<String, Object?> environment) {
  return '''// Generated by tool/env_tool.dart from config.local.json.
// DO NOT EDIT. Edit config.local.json and run `make env-gettoken`.
const Map<String, Object?> environment = ${_dartLiteral(environment)};
''';
}

String _dartLiteral(Object? value, [int depth = 0]) {
  final indent = '  ' * depth;
  final childIndent = '  ' * (depth + 1);
  if (value == null || value is num || value is bool) return '$value';
  if (value is String) return jsonEncode(value).replaceAll(r'$', r'\$');
  if (value is List) {
    if (value.isEmpty) return '<Object?>[]';
    return '<Object?>[\n$childIndent${value.map((item) => _dartLiteral(item, depth + 1)).join(',\n$childIndent')},\n$indent]';
  }
  if (value is Map) {
    if (value.isEmpty) return '<String, Object?>{}';
    final entries = value.entries.map(
      (entry) =>
          '${_dartLiteral(entry.key.toString())}: ${_dartLiteral(entry.value, depth + 1)}',
    );
    return '<String, Object?>{\n$childIndent${entries.join(',\n$childIndent')},\n$indent}';
  }
  throw ArgumentError('Unsupported environment value: ${value.runtimeType}');
}

class TokenClient {
  TokenClient({HttpClient? httpClient})
      : _httpClient = httpClient ?? HttpClient();

  final HttpClient _httpClient;

  Future<String> fetchAppToken(Map<String, dynamic> config) async {
    final response = await _postToken(
      config,
      <String, Object?>{
        'grant_type': 'client_credentials',
        'client_id': config['clientId'],
        'client_secret': config['clientSecret'],
      },
    );
    return _accessToken(response, 'app token');
  }

  Future<List<Map<String, Object?>>> fetchUserTokens({
    required Map<String, dynamic> config,
    required String appToken,
  }) async {
    final ttl = config['tokenTtl'];
    final rawAccounts =
        config['accounts'] is List ? config['accounts'] as List : const [];
    final accounts = <Map<String, Object?>>[];
    for (var index = 0; index < rawAccounts.length; index++) {
      final rawAccount = rawAccounts[index];
      if (rawAccount is! Map) {
        throw FormatException('accounts[$index] must be an object');
      }
      final userId = rawAccount['id'];
      if (_isPlaceholder(userId)) {
        throw FormatException(
          'accounts[$index].id is missing or still a "$_placeholderPrefix" '
          'placeholder',
        );
      }
      final body = <String, Object?>{
        'username': userId,
        'grant_type': 'inherit',
        'autoCreateUser': true,
        if (ttl is int) 'ttl': ttl,
      };
      final response = await _postToken(config, body, bearer: appToken);
      accounts.add({
        for (final entry in rawAccount.entries)
          if (entry.key != 'cluster') entry.key.toString(): entry.value,
        'token': _accessToken(response, 'user token for $userId'),
      });
      stdout.writeln('$userId token ok');
    }
    return accounts;
  }

  Future<Map<String, dynamic>> _postToken(
    Map<String, dynamic> config,
    Map<String, Object?> body, {
    String? bearer,
  }) async {
    final appKey = config['appKey'].toString().split('#');
    if (appKey.length != 2 || appKey.any((part) => part.isEmpty)) {
      throw FormatException(
        'invalid appKey, expected orgName#appName: ${config['appKey']}',
      );
    }
    final base = config['restApi'].toString().replaceFirst(RegExp(r'/+$'), '');
    final uri = Uri.parse('$base/${appKey[0]}/${appKey[1]}/token');
    final request = await _httpClient.postUrl(uri);
    request.headers.contentType = ContentType.json;
    request.headers.set(HttpHeaders.acceptHeader, ContentType.json.mimeType);
    if (bearer != null) {
      request.headers.set(HttpHeaders.authorizationHeader, 'Bearer $bearer');
    }
    request.write(jsonEncode(body));
    final response = await request.close();
    final text = await utf8.decoder.bind(response).join();
    Object? decoded;
    try {
      decoded = jsonDecode(text);
    } on FormatException {
      throw HttpException(
        'HTTP ${response.statusCode}: ${text.substring(0, text.length.clamp(0, 200).toInt())}',
        uri: uri,
      );
    }
    if (response.statusCode < 200 || response.statusCode >= 300) {
      final error = decoded is Map
          ? '${decoded['error'] ?? ''} ${decoded['error_description'] ?? ''}'
              .trim()
          : decoded.toString();
      throw HttpException('HTTP ${response.statusCode}: $error', uri: uri);
    }
    return Map<String, dynamic>.from(decoded as Map);
  }

  String _accessToken(Map<String, dynamic> response, String label) {
    final token = response['access_token'];
    if (token is! String || token.isEmpty) {
      throw FormatException('$label response missing access_token');
    }
    return token;
  }

  void close() => _httpClient.close(force: true);
}

Future<Map<String, dynamic>> _readJsonObject(File file) async {
  final decoded = jsonDecode(await file.readAsString());
  if (decoded is! Map) {
    throw FormatException('${file.path} must contain a JSON object');
  }
  return Map<String, dynamic>.from(decoded);
}

Map<String, Object?> _optionalMap(Object? value) {
  if (value is! Map) return <String, Object?>{};
  return <String, Object?>{
    for (final entry in value.entries) entry.key.toString(): entry.value,
  };
}

void _validateConfigShape(Map<String, dynamic> config) {
  if (config.containsKey('clusters') || config.containsKey('defaultCluster')) {
    throw const FormatException(
      'config.local.json still uses the removed multi-cluster shape; put '
      'restApi, appKey, clientId and clientSecret at the top level and drop '
      'defaultCluster and the per-entry cluster fields',
    );
  }
}

void _requireCredentials(Map<String, dynamic> config) {
  final missing = <String>[
    for (final key in const ['restApi', 'appKey', 'clientId', 'clientSecret'])
      if (_isPlaceholder(config[key])) key,
  ];
  if (missing.isNotEmpty) {
    throw FormatException(
      'config.local.json is missing ${missing.join(', ')}; fill in the '
      'environment you test against and run `make env-gettoken` again',
    );
  }
}

bool _isPlaceholder(Object? value) {
  return value is! String ||
      value.isEmpty ||
      value.startsWith(_placeholderPrefix);
}

Future<void> _atomicWrite(File target, String content) async {
  await target.parent.create(recursive: true);
  final temporary = File('${target.path}.tmp');
  await temporary.writeAsString(content, flush: true);
  await temporary.rename(target.path);
  await _restrictPermissions(target);
}

Future<void> _restrictPermissions(File file) async {
  if (!Platform.isWindows) {
    await Process.run('chmod', ['600', file.path]);
  }
}
