artifacts:
  web:
    5.0.0:
      path: ../web_runner/dist
      manifest: artifact_manifests/web-5.0.0.json
      flavor: main
      application_id: native-auto-test-web-runner
  ios:
    5.0.0:
      path: ../../im_flutter_test/build/ios/iphonesimulator/Runner.app
      manifest: artifact_manifests/ios-5.0.0.json
      flavor: main
      application_id: com.easemob.imFlutterTest
  android:
    5.0.0:
      path: ../../im_flutter_test/build/app/outputs/flutter-apk/app-debug.apk
      manifest: artifact_manifests/android-5.0.0.json
      flavor: main
      application_id: com.easemob.im_flutter_test
      activity: .MainActivity
