"""
SDK API 方法名枚举，与 im_flutter_sdk ChatMethodKeys 一一对应。
用于请求时的 cmd 字段，保证与 Flutter 端一致。
"""
from enum import Enum


class Cmd(str, Enum):
    """环信 Flutter SDK 方法名（cmd），与 chat_method_keys.dart 对应。"""

    # ----- EMClient -----
    init = "init"
    createAccount = "createAccount"
    login = "login"
    loginWithAgoraToken = "loginWithAgoraToken"
    renewToken = "renewToken"
    logout = "logout"
    changeAppKey = "changeAppKey"
    uploadLog = "uploadLog"
    compressLogs = "compressLogs"
    kickDevice = "kickDevice"
    kickAllDevices = "kickAllDevices"
    getLoggedInDevicesFromServer = "getLoggedInDevicesFromServer"
    getToken = "getToken"
    getCurrentUser = "getCurrentUser"
    getCurrentDeviceId = "getCurrentDeviceId"
    isLoggedInBefore = "isLoggedInBefore"
    isConnected = "isConnected"

    # ----- EMClient listener (callback keys) -----
    onMultiDeviceGroupEvent = "onMultiDeviceGroupEvent"
    onMultiDeviceContactEvent = "onMultiDeviceContactEvent"
    onMultiDeviceThreadEvent = "onMultiDeviceThreadEvent"
    onMultiDeviceRemoveMessagesEvent = "onMultiDeviceRemoveMessagesEvent"
    onMultiDevicesConversationEvent = "onMultiDevicesConversationEvent"
    onConnected = "onConnected"
    onDisconnected = "onDisconnected"
    onUserDidLoginFromOtherDevice = "onUserDidLoginFromOtherDevice"
    onUserDidRemoveFromServer = "onUserDidRemoveFromServer"
    onUserDidForbidByServer = "onUserDidForbidByServer"
    onUserDidChangePassword = "onUserDidChangePassword"
    onUserDidLoginTooManyDevice = "onUserDidLoginTooManyDevice"
    onUserKickedByOtherDevice = "onUserKickedByOtherDevice"
    onUserAuthenticationFailed = "onUserAuthenticationFailed"
    onSendDataToFlutter = "onSendDataToFlutter"
    onTokenWillExpire = "onTokenWillExpire"
    onTokenDidExpire = "onTokenDidExpire"
    onAppActiveNumberReachLimit = "onAppActiveNumberReachLimit"

    # ----- EMContactManager -----
    addContact = "addContact"
    deleteContact = "deleteContact"
    getAllContactsFromServer = "getAllContactsFromServer"
    getAllContactsFromDB = "getAllContactsFromDB"
    addUserToBlockList = "addUserToBlockList"
    removeUserFromBlockList = "removeUserFromBlockList"
    getBlockListFromServer = "getBlockListFromServer"
    getBlockListFromDB = "getBlockListFromDB"
    acceptInvitation = "acceptInvitation"
    declineInvitation = "declineInvitation"
    getSelfIdsOnOtherPlatform = "getSelfIdsOnOtherPlatform"
    getAllContacts = "getAllContacts"
    setContactRemark = "setContactRemark"
    getContact = "getContact"
    fetchAllContacts = "fetchAllContacts"
    fetchContacts = "fetchContacts"
    fetchAllContactIds = "fetchAllContactIds"
    getAllContactIds = "getAllContactIds"
    onContactChanged = "onContactChanged"

    # ----- EMChatManager -----
    sendMessage = "sendMessage"
    sendMessageWithType = "sendMessageWithType"
    resendMessage = "resendMessage"
    ackMessageRead = "ackMessageRead"
    ackGroupMessageRead = "ackGroupMessageRead"
    ackConversationRead = "ackConversationRead"
    recallMessage = "recallMessage"
    getConversation = "getConversation"
    getThreadConversation = "getThreadConversation"
    markAllChatMsgAsRead = "markAllChatMsgAsRead"
    getUnreadMessageCount = "getUnreadMessageCount"
    updateChatMessage = "updateChatMessage"
    downloadAttachment = "downloadAttachment"
    downloadThumbnail = "downloadThumbnail"
    downloadMessageAttachmentInCombine = "downloadMessageAttachmentInCombine"
    downloadMessageThumbnailInCombine = "downloadMessageThumbnailInCombine"
    importMessages = "importMessages"
    loadAllConversations = "loadAllConversations"
    getAllConversationsBySort = "getAllConversationsBySort"
    getConversationsFromServer = "getConversationsFromServer"
    deleteConversation = "deleteConversation"
    fetchHistoryMessages = "fetchHistoryMessages"
    fetchHistoryMessagesByOptions = "fetchHistoryMessagesByOptions"
    searchChatMsgFromDB = "searchChatMsgFromDB"
    getMessage = "getMessage"
    asyncFetchGroupAcks = "asyncFetchGroupAcks"
    deleteRemoteConversation = "deleteRemoteConversation"
    deleteMessagesBeforeTimestamp = "deleteMessagesBeforeTimestamp"
    translateMessage = "translateMessage"
    fetchSupportLanguages = "fetchSupportLanguages"
    addReaction = "addReaction"
    removeReaction = "removeReaction"
    fetchReactionList = "fetchReactionList"
    fetchReactionDetail = "fetchReactionDetail"
    reportMessage = "reportMessage"
    fetchConversationsFromServerWithPage = "fetchConversationsFromServerWithPage"
    removeMessagesFromServerWithMsgIds = "removeMessagesFromServerWithMsgIds"
    removeMessagesFromServerWithTs = "removeMessagesFromServerWithTs"
    getConversationsFromServerWithCursor = "getConversationsFromServerWithCursor"
    getPinnedConversationsFromServerWithCursor = "getPinnedConversationsFromServerWithCursor"
    pinConversation = "pinConversation"
    modifyMessage = "modifyMessage"
    downloadAndParseCombineMessage = "downloadAndParseCombineMessage"
    onMessagesReceived = "onMessagesReceived"
    onStreamMessagesReceived = "onStreamMessagesReceived"
    onCmdMessagesReceived = "onCmdMessagesReceived"
    onMessagesRead = "onMessagesRead"
    onReadAckForGroupMessageUpdated = "onReadAckForGroupMessageUpdated"
    onGroupMessageRead = "onGroupMessageRead"
    onMessagesDelivered = "onMessagesDelivered"
    onMessagesRecalled = "onMessagesRecalled"
    onMessageChanged = "onMessageChanged"
    onConversationUpdate = "onConversationUpdate"
    onConversationHasRead = "onConversationHasRead"
    onMessageReactionDidChange = "messageReactionDidChange"
    onMessageContentChanged = "onMessageContentChanged"
    onMessageProgressUpdate = "onMessageProgressUpdate"
    onMessageError = "onMessageError"
    onMessageSuccess = "onMessageSuccess"
    onMessageReadAck = "onMessageReadAck"
    onMessageDeliveryAck = "onMessageDeliveryAck"
    onPresenceStatusChanged = "onPresenceStatusChanged"

    # ----- EMConversation -----
    getUnreadMsgCount = "getUnreadMsgCount"
    markAllMessagesAsRead = "markAllMessagesAsRead"
    markMessageAsRead = "markMessageAsRead"
    syncConversationExt = "syncConversationExt"
    removeMessage = "removeMessage"
    deleteMessageByIds = "deleteMessageByIds"
    getLatestMessage = "getLatestMessage"
    getLatestMessageFromOthers = "getLatestMessageFromOthers"
    clearAllMessages = "clearAllMessages"
    deleteMessagesWithTs = "deleteMessagesWithTs"
    insertMessage = "insertMessage"
    appendMessage = "appendMessage"
    updateConversationMessage = "updateConversationMessage"
    loadMsgWithId = "loadMsgWithId"
    loadMsgWithStartId = "loadMsgWithStartId"
    loadMsgWithKeywords = "loadMsgWithKeywords"
    loadMsgWithMsgType = "loadMsgWithMsgType"
    loadMsgWithTime = "loadMsgWithTime"
    messageCount = "messageCount"
    removeMsgFromServerWithTimeStamp = "removeMsgFromServerWithTimeStamp"
    getReactionList = "getReactionList"
    groupAckCount = "groupAckCount"
    getChatThread = "chatThread"

    # ----- EMChatRoomManager -----
    joinChatRoom = "joinChatRoom"
    leaveChatRoom = "leaveChatRoom"
    fetchPublicChatRoomsFromServer = "fetchPublicChatRoomsFromServer"
    fetchChatRoomInfoFromServer = "fetchChatRoomInfoFromServer"
    getChatRoom = "getChatRoom"
    getAllChatRooms = "getAllChatRooms"
    createChatRoom = "createChatRoom"
    destroyChatRoom = "destroyChatRoom"
    changeChatRoomSubject = "changeChatRoomSubject"
    changeChatRoomDescription = "changeChatRoomDescription"
    fetchChatRoomMembers = "fetchChatRoomMembers"
    muteChatRoomMembers = "muteChatRoomMembers"
    unMuteChatRoomMembers = "unMuteChatRoomMembers"
    changeChatRoomOwner = "changeChatRoomOwner"
    addChatRoomAdmin = "addChatRoomAdmin"
    removeChatRoomAdmin = "removeChatRoomAdmin"
    fetchChatRoomMuteList = "fetchChatRoomMuteList"
    removeChatRoomMembers = "removeChatRoomMembers"
    blockChatRoomMembers = "blockChatRoomMembers"
    unBlockChatRoomMembers = "unBlockChatRoomMembers"
    fetchChatRoomBlockList = "fetchChatRoomBlockList"
    updateChatRoomAnnouncement = "updateChatRoomAnnouncement"
    fetchChatRoomAnnouncement = "fetchChatRoomAnnouncement"
    addMembersToChatRoomWhiteList = "addMembersToChatRoomWhiteList"
    removeMembersFromChatRoomWhiteList = "removeMembersFromChatRoomWhiteList"
    fetchChatRoomWhiteListFromServer = "fetchChatRoomWhiteListFromServer"
    isMemberInChatRoomWhiteListFromServer = "isMemberInChatRoomWhiteListFromServer"
    muteAllChatRoomMembers = "muteAllChatRoomMembers"
    unMuteAllChatRoomMembers = "unMuteAllChatRoomMembers"
    fetchChatRoomAttributes = "fetchChatRoomAttributes"
    setChatRoomAttributes = "setChatRoomAttributes"
    removeChatRoomAttributes = "removeChatRoomAttributes"
    chatRoomChange = "onChatRoomChanged"

    # ----- EMGroupManager -----
    getGroupWithId = "getGroupWithId"
    getJoinedGroups = "getJoinedGroups"
    getJoinedGroupsFromServer = "getJoinedGroupsFromServer"
    getPublicGroupsFromServer = "getPublicGroupsFromServer"
    createGroup = "createGroup"
    getGroupSpecificationFromServer = "getGroupSpecificationFromServer"
    getGroupMemberListFromServer = "getGroupMemberListFromServer"
    getGroupBlockListFromServer = "getGroupBlockListFromServer"
    getGroupMuteListFromServer = "getGroupMuteListFromServer"
    getGroupWhiteListFromServer = "getGroupWhiteListFromServer"
    isMemberInWhiteListFromServer = "isMemberInWhiteListFromServer"
    getGroupFileListFromServer = "getGroupFileListFromServer"
    getGroupAnnouncementFromServer = "getGroupAnnouncementFromServer"
    addMembers = "addMembers"
    inviterUser = "inviterUser"
    removeMembers = "removeMembers"
    blockMembers = "blockMembers"
    unblockMembers = "unblockMembers"
    updateGroupSubject = "updateGroupSubject"
    updateDescription = "updateDescription"
    leaveGroup = "leaveGroup"
    destroyGroup = "destroyGroup"
    blockGroup = "blockGroup"
    unblockGroup = "unblockGroup"
    updateGroupOwner = "updateGroupOwner"
    addAdmin = "addAdmin"
    removeAdmin = "removeAdmin"
    muteMembers = "muteMembers"
    unMuteMembers = "unMuteMembers"
    muteAllMembers = "muteAllMembers"
    unMuteAllMembers = "unMuteAllMembers"
    addWhiteList = "addWhiteList"
    removeWhiteList = "removeWhiteList"
    uploadGroupSharedFile = "uploadGroupSharedFile"
    downloadGroupSharedFile = "downloadGroupSharedFile"
    removeGroupSharedFile = "removeGroupSharedFile"
    updateGroupAnnouncement = "updateGroupAnnouncement"
    updateGroupExt = "updateGroupExt"
    joinPublicGroup = "joinPublicGroup"
    requestToJoinPublicGroup = "requestToJoinPublicGroup"
    acceptJoinApplication = "acceptJoinApplication"
    declineJoinApplication = "declineJoinApplication"
    acceptInvitationFromGroup = "acceptInvitationFromGroup"
    declineInvitationFromGroup = "declineInvitationFromGroup"
    setMemberAttributesFromGroup = "setMemberAttributesFromGroup"
    removeMemberAttributesFromGroup = "removeMemberAttributesFromGroup"
    fetchMemberAttributesFromGroup = "fetchMemberAttributesFromGroup"
    fetchMembersAttributesFromGroup = "fetchMembersAttributesFromGroup"
    fetchJoinedGroupCount = "fetchJoinedGroupCount"
    onGroupChanged = "onGroupChanged"

    # ----- EMPushManager -----
    getImPushConfig = "getImPushConfig"
    getImPushConfigFromServer = "getImPushConfigFromServer"
    updateImPushStyle = "updateImPushStyle"
    updatePushNickname = "updatePushNickname"
    updateHMSPushToken = "updateHMSPushToken"
    updateFCMPushToken = "updateFCMPushToken"
    updateAPNsPushToken = "updateAPNsPushToken"
    reportPushAction = "reportPushAction"
    setConversationSilentMode = "setConversationSilentMode"
    removeConversationSilentMode = "removeConversationSilentMode"
    fetchConversationSilentMode = "fetchConversationSilentMode"
    setSilentModeForAll = "setSilentModeForAll"
    fetchSilentModeForAll = "fetchSilentModeForAll"
    fetchSilentModeForConversations = "fetchSilentModeForConversations"
    setPreferredNotificationLanguage = "setPreferredNotificationLanguage"
    fetchPreferredNotificationLanguage = "fetchPreferredNotificationLanguage"
    setPushTemplate = "setPushTemplate"
    getPushTemplate = "getPushTemplate"

    # ----- EMUserInfoManager -----
    updateOwnUserInfo = "updateOwnUserInfo"
    updateOwnUserInfoWithType = "updateOwnUserInfoWithType"
    fetchOwnInfo = "fetchOwnInfo"
    fetchUserInfoById = "fetchUserInfoById"
    fetchUserInfoByIdWithType = "fetchUserInfoByIdWithType"

    # ----- EMPresenceManager -----
    presenceWithDescription = "publishPresenceWithDescription"
    presenceSubscribe = "presenceSubscribe"
    presenceUnsubscribe = "presenceUnsubscribe"
    fetchSubscribedMembersWithPageNum = "fetchSubscribedMembersWithPageNum"
    fetchPresenceStatus = "fetchPresenceStatus"

    # ----- EMChatThreadManager -----
    fetchChatThreadDetail = "fetchChatThreadDetail"
    fetchJoinedChatThreads = "fetchJoinedChatThreads"
    fetchChatThreadsWithParentId = "fetchChatThreadsWithParentId"
    fetchJoinedChatThreadsWithParentId = "fetchJoinedChatThreadsWithParentId"
    fetchChatThreadMember = "fetchChatThreadMember"
    fetchLastMessageWithChatThreads = "fetchLastMessageWithChatThreads"
    removeMemberFromChatThread = "removeMemberFromChatThread"
    updateChatThreadSubject = "updateChatThreadSubject"
    createChatThread = "createChatThread"
    joinChatThread = "joinChatThread"
    leaveChatThread = "leaveChatThread"
    destroyChatThread = "destroyChatThread"
    onChatThreadCreate = "onChatThreadCreate"
    onChatThreadUpdate = "onChatThreadUpdate"
    onChatThreadDestroy = "onChatThreadDestroy"
    onUserKickOutOfChatThread = "onUserKickOutOfChatThread"

    startCallback = "startCallback"

    # ----- 450+ -----
    getPinInfo = "getPinInfo"
    pinnedMessages = "pinnedMessages"
    onMessagePinChanged = "onMessagePinChanged"
    addRemoteAndLocalConversationsMark = "addRemoteAndLocalConversationsMark"
    deleteRemoteAndLocalConversationsMark = "deleteRemoteAndLocalConversationsMark"
    fetchConversationsByOptions = "fetchConversationsByOptions"
    deleteAllMessageAndConversation = "deleteAllMessageAndConversation"
    pinMessage = "pinMessage"
    unpinMessage = "unpinMessage"
    fetchPinnedMessages = "fetchPinnedMessages"
    onMessagesRecalledInfo = "onMessagesRecalledInfo"

    conversationRemindType = "conversationRemindType"
    conversationSearchMsgsByOptions = "conversationSearchMsgsByOptions"
    conversationGetLocalMessageCount = "conversationGetLocalMessageCount"
    conversationDeleteServerMessageWithIds = "conversationDeleteServerMessageWithIds"
    conversationDeleteServerMessageWithTime = "conversationDeleteServerMessageWithTime"
    searchMsgsByOptions = "searchMsgsByOptions"
    syncSilentModels = "syncSilentModels"
    clearAllGroupsFromDB = "clearAllGroupsFromDB"
    updateUsingHttpsOnlySetting = "updateUsingHttpsOnlySetting"
    updateLoginExtensionInfo = "updateLoginExtensionInfo"
    updateDeleteMessagesWhenLeaveGroupSetting = "updateDeleteMessagesWhenLeaveGroupSetting"
    updateDeleteMessageWhenLeaveRoomSetting = "updateDeleteMessageWhenLeaveRoomSetting"
    updateRoomOwnerCanLeaveSetting = "updateRoomOwnerCanLeaveSetting"
    updateAutoAcceptGroupInvitationSetting = "updateAutoAcceptGroupInvitationSetting"
    updateAcceptInvitationAlways = "acceptInvitationAlways"
    updateAutoDownloadAttachmentThumbnailSetting = "updateAutoDownloadAttachmentThumbnailSetting"
    updateRequireAckSetting = "updateRequireAckSetting"
    updateDeliveryAckSetting = "updateDeliveryAckSetting"
    updateSortMessageByServerTimeSetting = "updateSortMessageByServerTimeSetting"
    updateMessagesReceiveCallbackIncludeSendSetting = "updateMessagesReceiveCallbackIncludeSendSetting"
    updateRegradeMessagesSetting = "updateRegradeMessagesSetting"
    bindDeviceToken = "bindDeviceToken"

    onOfflineMessageSyncStart = "onOfflineMessageSyncStart"
    onOfflineMessageSyncFinish = "onOfflineMessageSyncFinish"
    getMessageCount = "getMessageCount"
    isMemberInGroupMuteList = "isMemberInGroupMuteList"
    changeAppId = "changeAppId"
    isMemberInChatRoomMuteList = "isMemberInChatRoomMuteList"
    fetchGroupMembersInfo = "fetchGroupMembersInfo"
    updateGroupAvatar = "updateGroupAvatar"
    loadConversationMessagesWithKeyword = "loadConversationMessagesWithKeyword"
    loadMessagesWithIds = "loadMessagesWithIds"
